# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 19:47
from __future__ import unicode_literals

import blog.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Public'), ('D', 'Draft'), ('O', 'Own'), ('S', 'Secret')], default='D', max_length=3)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('permission_text', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 47, 34, 966604))),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managing.Category')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managing.Locale')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_tags', to='managing.Tag')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
