# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 47, 42, 443520)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Public'), ('S', 'Secret'), ('D', 'Draft'), ('O', 'Own')], default='D', max_length=3),
        ),
    ]
