# Generated by Django 2.0.2 on 2018-10-02 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 14, 41, 5, 878013)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('S', 'Secret'), ('P', 'Public'), ('O', 'Own'), ('D', 'Draft')], default='D', max_length=3),
        ),
    ]
