# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180118_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 48, 19, 858810)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('O', 'Own'), ('S', 'Secret'), ('D', 'Draft'), ('P', 'Public')], default='D', max_length=3),
        ),
    ]
