# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180118_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 50, 10, 157043)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('O', 'Own'), ('P', 'Public'), ('D', 'Draft'), ('S', 'Secret')], default='D', max_length=3),
        ),
    ]
