# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180118_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 3, 49, 36, 980533)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('O', 'Own'), ('D', 'Draft'), ('P', 'Public'), ('S', 'Secret')], default='D', max_length=3),
        ),
    ]
