# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180121_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 23, 7, 7, 876145)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('S', 'Secret'), ('D', 'Draft'), ('O', 'Own'), ('P', 'Public')], default='D', max_length=3),
        ),
    ]
