# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180214_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 42, 58, 595790)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Public'), ('O', 'Own'), ('D', 'Draft'), ('S', 'Secret')], default='D', max_length=3),
        ),
    ]
