# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180223_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 45, 48, 693706)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Public'), ('S', 'Secret'), ('D', 'Draft'), ('O', 'Own')], default='D', max_length=3),
        ),
    ]
