# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180223_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 11, 17, 452172)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('O', 'Own'), ('S', 'Secret'), ('P', 'Public'), ('D', 'Draft')], default='D', max_length=3),
        ),
    ]
