# Generated by Django 2.0.2 on 2018-02-28 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180227_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 8, 39, 31, 72142)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Public'), ('O', 'Own'), ('S', 'Secret'), ('D', 'Draft')], default='D', max_length=3),
        ),
    ]
