# Generated by Django 2.0.2 on 2018-06-03 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180301_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 15, 37, 1, 790066)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Public'), ('D', 'Draft'), ('O', 'Own'), ('S', 'Secret')], default='D', max_length=3),
        ),
    ]
