# Generated by Django 2.0.2 on 2018-09-11 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180911_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 20, 0, 45, 305756)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('O', 'Own'), ('P', 'Public'), ('D', 'Draft'), ('S', 'Secret')], default='D', max_length=3),
        ),
    ]
