# Generated by Django 2.0.2 on 2018-10-02 08:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rightnow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('mood', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('O', 'Own'), ('P', 'Public'), ('A', 'Archive')], default='P', max_length=3)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 10, 2, 14, 40, 49, 630992))),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managing.Locale')),
            ],
        ),
    ]
