# Generated by Django 2.0.2 on 2018-09-11 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightnow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightnow',
            name='content',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rightnow',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 20, 0, 45, 319875)),
        ),
        migrations.AlterField(
            model_name='rightnow',
            name='status',
            field=models.CharField(choices=[('O', 'Own'), ('A', 'Archive'), ('P', 'Public')], default='P', max_length=3),
        ),
    ]
