# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcampus', '0003_auto_20180118_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 50, 10, 163566)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 50, 10, 160400)),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('1', 'Elementary'), ('3', 'Advanced'), ('2', 'Intermediate'), ('0', 'Beginner')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('H', 'Hidden'), ('A', 'Archive'), ('V', 'Visible')], default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='htmlblock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 50, 10, 165940)),
        ),
        migrations.AlterField(
            model_name='step',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 50, 10, 164164)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 50, 10, 159540)),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 50, 10, 165409)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 1, 50, 10, 166577)),
        ),
    ]
