# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcampus', '0004_auto_20180118_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 3, 49, 36, 989948)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 3, 49, 36, 986646)),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('0', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('1', 'Elementary')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='htmlblock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 3, 49, 36, 992327)),
        ),
        migrations.AlterField(
            model_name='step',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 3, 49, 36, 990544)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 3, 49, 36, 984736)),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 3, 49, 36, 991738)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 3, 49, 36, 992857)),
        ),
    ]
