# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcampus', '0005_auto_20180121_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 2, 14, 23, 7, 7, 879448))),
            ],
            options={
                'verbose_name': 'Траектория',
                'verbose_name_plural': 'Траектории',
            },
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 23, 7, 7, 885369)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 23, 7, 7, 880783)),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('1', 'Elementary'), ('2', 'Intermediate'), ('0', 'Beginner'), ('3', 'Advanced')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('V', 'Visible'), ('H', 'Hidden'), ('A', 'Archive')], default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='htmlblock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 23, 7, 7, 887975)),
        ),
        migrations.AlterField(
            model_name='step',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 23, 7, 7, 885994)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 23, 7, 7, 878937)),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 23, 7, 7, 887408)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 23, 7, 7, 888544)),
        ),
        migrations.AddField(
            model_name='course',
            name='trajectory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcampus.Trajectory'),
        ),
    ]
