# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 11:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcampus', '0006_auto_20180214_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='webcampus.Course'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 42, 58, 608933)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 42, 58, 601292)),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('0', 'Beginner'), ('1', 'Elementary'), ('2', 'Intermediate'), ('3', 'Advanced')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('A', 'Archive'), ('H', 'Hidden'), ('V', 'Visible')], default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='htmlblock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 42, 58, 611805)),
        ),
        migrations.AlterField(
            model_name='step',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='webcampus.Chapter'),
        ),
        migrations.AlterField(
            model_name='step',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 42, 58, 609671)),
        ),
        migrations.AlterField(
            model_name='step',
            name='done',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 42, 58, 599770)),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 42, 58, 611203)),
        ),
        migrations.AlterField(
            model_name='trajectory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 42, 58, 600330)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 42, 58, 612432)),
        ),
    ]
