# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcampus', '0008_auto_20180223_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='title_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 11, 17, 459279)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 11, 17, 456214)),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('0', 'Beginner'), ('2', 'Intermediate'), ('1', 'Elementary'), ('3', 'Advanced')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('V', 'Visible'), ('A', 'Archive'), ('H', 'Hidden')], default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='htmlblock',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 11, 17, 461808)),
        ),
        migrations.AlterField(
            model_name='step',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 11, 17, 459877)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 11, 17, 454808)),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 11, 17, 461269)),
        ),
        migrations.AlterField(
            model_name='trajectory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 11, 17, 455294)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 11, 17, 462957)),
        ),
    ]
