# Generated by Django 2.0.2 on 2018-10-02 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 10, 2, 14, 40, 49, 614939))),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('translit', models.CharField(max_length=15)),
                ('original', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 10, 2, 14, 40, 49, 616462))),
            ],
            options={
                'verbose_name': 'Локаль',
                'verbose_name_plural': 'Локали',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 10, 2, 14, 40, 49, 615670))),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
