# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0007_auto_20180223_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 45, 48, 691308)),
        ),
        migrations.AlterField(
            model_name='locale',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 45, 48, 692600)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 17, 45, 48, 691816)),
        ),
    ]
