# Generated by Django 2.0.2 on 2018-09-11 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0016_auto_20180911_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 20, 0, 45, 304001)),
        ),
        migrations.AlterField(
            model_name='locale',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 20, 0, 45, 304978)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 20, 0, 45, 304490)),
        ),
    ]
